var INICIO_0 = 0; 
var INICIO = 4;
var AJUSTA_SOLICITACAO = 14;
var APROVACAO_COORD_PLAN = 99;
var APROVACAO_GERENTE = 55;
var APROVACAO_COORD_PLAN_REV = 115;
var APROVACAO_GERENTE_REV = 119;
var INFORMAR_RESP_VINCULACAO = 5;
var SCRIPT_INICIAR_FILHAS = 26;
var ACOMPANHAR_SOLICITACAO_REVISAO = 49;
var INTEMEDIARIO = 28;
var SUPORTE_TI = 31;
var SUPORTE_TI_RM = 78;
//ATIVIDADES FIM
var FIM = 16;
var FIM_REPROVADO = 62;
//ATIVIDADES DECISORIAS
var DECISORIA_VALIDAR_ABERTURA = 64;
var DECISORIA_AJUSTES = 38;
var DECISORIA_VALIDAR = 45;
var EXCLUSIVO_ACOMPANHAR_REV = 113;